/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { IdeaService } from "../idea.service";
import { IdeaCreateInput } from "./IdeaCreateInput";
import { Idea } from "./Idea";
import { IdeaFindManyArgs } from "./IdeaFindManyArgs";
import { IdeaWhereUniqueInput } from "./IdeaWhereUniqueInput";
import { IdeaUpdateInput } from "./IdeaUpdateInput";

export class IdeaControllerBase {
  constructor(protected readonly service: IdeaService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Idea })
  async createIdea(@common.Body() data: IdeaCreateInput): Promise<Idea> {
    return await this.service.createIdea({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Idea] })
  @ApiNestedQuery(IdeaFindManyArgs)
  async ideas(@common.Req() request: Request): Promise<Idea[]> {
    const args = plainToClass(IdeaFindManyArgs, request.query);
    return this.service.ideas({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Idea })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async idea(
    @common.Param() params: IdeaWhereUniqueInput
  ): Promise<Idea | null> {
    const result = await this.service.idea({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Idea })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateIdea(
    @common.Param() params: IdeaWhereUniqueInput,
    @common.Body() data: IdeaUpdateInput
  ): Promise<Idea | null> {
    try {
      return await this.service.updateIdea({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Idea })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteIdea(
    @common.Param() params: IdeaWhereUniqueInput
  ): Promise<Idea | null> {
    try {
      return await this.service.deleteIdea({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
